//! LLM-powered PRD decomposition via Claude CLI.
//!
//! This module provides automatic task graph generation by sending a PRD to Claude
//! and parsing the resulting task list with dependencies. The generated DAG is validated
//! for correctness (no cycles, valid references, unique IDs) before being returned.

use std::path::Path;
use std::collections::{HashMap, HashSet, VecDeque};
use serde::Deserialize;
use crate::core::task_dag::{Priority, Complexity};
use crate::queen::pipe_process::{PipeProcess, PipeProcessOptions};
use crate::queen::spawn_mode::ClaudeEvent;

// ============================================================================
// Types
// ============================================================================

/// A task generated by LLM decomposition of a PRD.
#[derive(Debug, Clone, Deserialize)]
pub struct GeneratedTask {
    pub id: String,
    pub description: String,
    pub dependencies: Vec<String>,
    pub task_type: TaskType,
    pub priority: Priority,
    pub complexity: Complexity,
    pub skill_hint: Option<String>,
}

/// Type of task in the decomposition.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TaskType {
    Research,
    Implement,
    Test,
    Debug,
    Refactor,
    Documentation,
    Infrastructure,
}

/// Errors that can occur during DAG generation.
#[derive(Debug, thiserror::Error)]
pub enum DagGenError {
    #[error("CLI process failed: {0}")]
    ProcessFailed(String),
    #[error("No result from CLI")]
    NoResult,
    #[error("JSON parse failed: {0}")]
    JsonParseFailed(String),
    #[error("DAG validation failed: {0}")]
    InvalidDag(String),
    #[error("Empty task list")]
    EmptyTaskList,
}

// ============================================================================
// Prompt Constant
// ============================================================================

const DECOMPOSITION_SYSTEM_PROMPT: &str = include_str!("prompts/decomposition_system.md");

// ============================================================================
// Core Function
// ============================================================================

/// Decompose a PRD into a task DAG using Claude CLI.
///
/// This function:
/// 1. Sends the PRD to Claude with decomposition instructions
/// 2. Polls for the result using NDJSON streaming
/// 3. Parses the JSON task list
/// 4. Validates the DAG for correctness
///
/// # Arguments
/// * `prd_content` - The PRD text to decompose
/// * `working_dir` - Working directory for the Claude process
///
/// # Returns
/// A validated list of tasks with dependencies, ready to be added to a TaskDag.
pub async fn decompose_prd(
    prd_content: &str,
    working_dir: &Path,
) -> Result<Vec<GeneratedTask>, DagGenError> {
    // User prompt = just the PRD text. All instructions go in system prompt.
    let prompt = format!("Decompose this PRD into tasks:\n\n{}", prd_content);

    let options = PipeProcessOptions {
        model: Some("sonnet".to_string()),
        max_turns: Some(2),
        // System prompt carries all decomposition instructions (overrides CLAUDE.md context)
        append_system_prompt: Some(DECOMPOSITION_SYSTEM_PROMPT.to_string()),
        no_project: Some(true),  // Don't load CLAUDE.md for decomposition
        ..Default::default()
    };

    let mut proc = PipeProcess::new_with_options(working_dir, &prompt, options, vec![])
        .map_err(|e| DagGenError::ProcessFailed(e.to_string()))?;

    let result_text = poll_for_result(&mut proc).await?;
    let tasks = parse_task_list(&result_text)?;
    validate_dag(&tasks)?;
    Ok(tasks)
}

// ============================================================================
// Helpers
// ============================================================================

/// Extract text content from a ClaudeEvent assistant message.
fn extract_assistant_text(event: &ClaudeEvent) -> Option<String> {
    let msg = event.message.as_ref()?;
    let content = msg.get("content")?.as_array()?;
    for block in content {
        if block.get("type")?.as_str()? == "text" {
            if let Some(text) = block.get("text").and_then(|t| t.as_str()) {
                if !text.trim().is_empty() {
                    return Some(text.to_string());
                }
            }
        }
    }
    None
}

// ============================================================================
// Polling
// ============================================================================

/// Poll the Claude CLI process for a result event.
///
/// Polls with 100ms sleep intervals, 60s total timeout.
/// Returns the result text from the final ClaudeEvent.
async fn poll_for_result(proc: &mut PipeProcess) -> Result<String, DagGenError> {
    use tokio::time::{sleep, Duration};

    let timeout = Duration::from_secs(60);
    let poll_interval = Duration::from_millis(100);
    let start = std::time::Instant::now();
    let mut last_assistant_text: Option<String> = None;

    loop {
        // Drain all available output FIRST (before checking process state)
        let mut got_output = false;
        while let Some(line) = proc.try_recv() {
            got_output = true;
            let line = line.trim();
            if line.is_empty() { continue; }
            eprintln!("[DAG decompose] NDJSON: {}...", &line[..line.len().min(120)]);

            if let Ok(event) = serde_json::from_str::<ClaudeEvent>(line) {
                // Track last assistant text (fallback if result field is empty)
                if event.event_type == "assistant" {
                    if let Some(text) = extract_assistant_text(&event) {
                        last_assistant_text = Some(text);
                    }
                }

                if event.is_result() {
                    let _ = proc.kill();
                    if let Some(result) = event.result {
                        return Ok(result);
                    }
                    if let Some(text) = last_assistant_text {
                        return Ok(text);
                    }
                    return Err(DagGenError::NoResult);
                }
            }
        }

        // Check timeout
        if start.elapsed() >= timeout {
            let _ = proc.kill();
            return Err(DagGenError::ProcessFailed("Timeout after 60s".to_string()));
        }

        // Check if process died (only after draining output)
        if !proc.is_running() && !got_output {
            // One final drain attempt
            while let Some(line) = proc.try_recv() {
                let line = line.trim();
                if line.is_empty() { continue; }
                if let Ok(event) = serde_json::from_str::<ClaudeEvent>(line) {
                    if event.event_type == "assistant" {
                        if let Some(text) = extract_assistant_text(&event) {
                            last_assistant_text = Some(text);
                        }
                    }
                    if event.is_result() {
                        if let Some(result) = event.result {
                            return Ok(result);
                        }
                        if let Some(text) = last_assistant_text {
                            return Ok(text);
                        }
                        return Err(DagGenError::NoResult);
                    }
                }
            }
            // If we have assistant text but no result event, try to use it
            if let Some(text) = last_assistant_text {
                return Ok(text);
            }
            return Err(DagGenError::ProcessFailed("Process exited without result".to_string()));
        }

        sleep(poll_interval).await;
    }
}

// ============================================================================
// Parsing
// ============================================================================

/// Parse the LLM response into a task list.
///
/// Handles:
/// - Plain JSON arrays
/// - JSON wrapped in markdown code fences (```json ... ```)
/// - Whitespace trimming
///
/// Returns EmptyTaskList if the array is empty.
fn parse_task_list(response: &str) -> Result<Vec<GeneratedTask>, DagGenError> {
    let trimmed = response.trim();
    eprintln!("[DAG decompose] Result text ({} chars): {}", trimmed.len(), &trimmed[..trimmed.len().min(500)]);

    // Extract JSON content — handle code fences, wrapper objects, bare arrays
    let json_str = extract_json_array(trimmed)?;

    // Parse JSON
    let tasks: Vec<GeneratedTask> = serde_json::from_str(json_str)
        .map_err(|e| DagGenError::JsonParseFailed(format!("{}: {}", e, &json_str[..json_str.len().min(200)])))?;

    if tasks.is_empty() {
        return Err(DagGenError::EmptyTaskList);
    }

    eprintln!("[DAG decompose] Parsed {} tasks", tasks.len());
    Ok(tasks)
}

/// Extract JSON array from LLM response, handling various formats:
/// - Bare JSON array: `[...]`
/// - Code-fenced: ````json [...] ````
/// - Wrapper object: `{"tasks": [...]}`
/// - Text before/after JSON
fn extract_json_array(text: &str) -> Result<&str, DagGenError> {
    let trimmed = text.trim();

    // Strip code fences if present
    let inner = if trimmed.starts_with("```") {
        let after_fence = trimmed.find('\n').map(|i| &trimmed[i+1..]).unwrap_or(trimmed);
        let end = after_fence.rfind("```").unwrap_or(after_fence.len());
        after_fence[..end].trim()
    } else {
        trimmed
    };

    // If it starts with '[', it's a bare array
    if inner.starts_with('[') {
        if let Some(end) = inner.rfind(']') {
            return Ok(&inner[..=end]);
        }
    }

    // If it starts with '{', might be a wrapper like {"tasks": [...]}
    // Find the first '[' and last ']' inside
    if inner.starts_with('{') || inner.contains('[') {
        let start = inner.find('[')
            .ok_or_else(|| DagGenError::JsonParseFailed("No JSON array found in response".to_string()))?;
        let end = inner.rfind(']')
            .ok_or_else(|| DagGenError::JsonParseFailed("No closing ] found in response".to_string()))?;
        return Ok(&inner[start..=end]);
    }

    Err(DagGenError::JsonParseFailed(format!(
        "Cannot find JSON array in response: {}",
        &inner[..inner.len().min(100)]
    )))
}

// ============================================================================
// Validation
// ============================================================================

/// Validate the task DAG for correctness.
///
/// Checks:
/// 1. Unique task IDs
/// 2. All dependencies reference existing tasks
/// 3. No self-references
/// 4. No cycles (using Kahn's algorithm)
fn validate_dag(tasks: &[GeneratedTask]) -> Result<(), DagGenError> {
    // 1. Check unique IDs
    let mut seen_ids = HashSet::new();
    for task in tasks {
        if !seen_ids.insert(&task.id) {
            return Err(DagGenError::InvalidDag(
                format!("Duplicate task ID: {}", task.id)
            ));
        }
    }

    // Build ID set for quick lookup
    let valid_ids: HashSet<&str> = tasks.iter().map(|t| t.id.as_str()).collect();

    // 2 & 3. Check dependency references and self-references
    for task in tasks {
        for dep_id in &task.dependencies {
            // Check self-reference
            if dep_id == &task.id {
                return Err(DagGenError::InvalidDag(
                    format!("Task {} depends on itself", task.id)
                ));
            }
            // Check reference exists
            if !valid_ids.contains(dep_id.as_str()) {
                return Err(DagGenError::InvalidDag(
                    format!("Task {} depends on non-existent task {}", task.id, dep_id)
                ));
            }
        }
    }

    // 4. Cycle detection using Kahn's algorithm (topological sort)
    let mut in_degree: HashMap<&str, usize> = HashMap::new();
    for task in tasks {
        in_degree.insert(&task.id, task.dependencies.len());
    }

    // Find all tasks with no dependencies
    let mut queue: VecDeque<&str> = tasks
        .iter()
        .filter(|t| t.dependencies.is_empty())
        .map(|t| t.id.as_str())
        .collect();

    let mut processed_count = 0;

    while let Some(task_id) = queue.pop_front() {
        processed_count += 1;

        // For each task that depends on this one, decrement in-degree
        for task in tasks {
            if task.dependencies.iter().any(|dep| dep == task_id) {
                if let Some(degree) = in_degree.get_mut(task.id.as_str()) {
                    *degree -= 1;
                    if *degree == 0 {
                        queue.push_back(&task.id);
                    }
                }
            }
        }
    }

    // If we processed all tasks, DAG is valid
    if processed_count == tasks.len() {
        Ok(())
    } else {
        Err(DagGenError::InvalidDag(
            "Cycle detected in task dependencies".to_string()
        ))
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn make_test_task(id: &str, deps: Vec<&str>) -> GeneratedTask {
        GeneratedTask {
            id: id.to_string(),
            description: format!("Task {}", id),
            dependencies: deps.into_iter().map(String::from).collect(),
            task_type: TaskType::Implement,
            priority: Priority::Normal,
            complexity: Complexity::Medium,
            skill_hint: None,
        }
    }

    #[test]
    fn test_parse_task_list_valid_json() {
        let json = r#"[
            {
                "id": "T1",
                "description": "Research API",
                "dependencies": [],
                "task_type": "research",
                "priority": "High",
                "complexity": "Simple",
                "skill_hint": null
            },
            {
                "id": "T2",
                "description": "Implement connector",
                "dependencies": ["T1"],
                "task_type": "implement",
                "priority": "Normal",
                "complexity": "Medium",
                "skill_hint": "rust-implementer"
            }
        ]"#;

        let tasks = parse_task_list(json).unwrap();
        assert_eq!(tasks.len(), 2);
        assert_eq!(tasks[0].id, "T1");
        assert_eq!(tasks[1].id, "T2");
        assert_eq!(tasks[1].dependencies, vec!["T1"]);
    }

    #[test]
    fn test_parse_task_list_with_code_fences() {
        let markdown = r#"```json
[
    {
        "id": "T1",
        "description": "First task",
        "dependencies": [],
        "task_type": "research",
        "priority": "Normal",
        "complexity": "Simple",
        "skill_hint": null
    }
]
```"#;

        let tasks = parse_task_list(markdown).unwrap();
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].id, "T1");
    }

    #[test]
    fn test_parse_task_list_empty_array() {
        let json = "[]";
        let result = parse_task_list(json);
        assert!(matches!(result, Err(DagGenError::EmptyTaskList)));
    }

    #[test]
    fn test_validate_dag_valid() {
        let tasks = vec![
            make_test_task("T1", vec![]),
            make_test_task("T2", vec!["T1"]),
            make_test_task("T3", vec!["T2"]),
        ];

        assert!(validate_dag(&tasks).is_ok());
    }

    #[test]
    fn test_validate_dag_duplicate_ids() {
        let tasks = vec![
            make_test_task("T1", vec![]),
            make_test_task("T1", vec![]), // Duplicate!
        ];

        let result = validate_dag(&tasks);
        assert!(matches!(result, Err(DagGenError::InvalidDag(_))));
        if let Err(DagGenError::InvalidDag(msg)) = result {
            assert!(msg.contains("Duplicate"));
        }
    }

    #[test]
    fn test_validate_dag_cycle() {
        let tasks = vec![
            GeneratedTask {
                id: "T1".to_string(),
                description: "First".to_string(),
                dependencies: vec!["T2".to_string()], // T1 depends on T2
                task_type: TaskType::Implement,
                priority: Priority::Normal,
                complexity: Complexity::Medium,
                skill_hint: None,
            },
            GeneratedTask {
                id: "T2".to_string(),
                description: "Second".to_string(),
                dependencies: vec!["T1".to_string()], // T2 depends on T1 -> cycle!
                task_type: TaskType::Implement,
                priority: Priority::Normal,
                complexity: Complexity::Medium,
                skill_hint: None,
            },
        ];

        let result = validate_dag(&tasks);
        assert!(matches!(result, Err(DagGenError::InvalidDag(_))));
        if let Err(DagGenError::InvalidDag(msg)) = result {
            assert!(msg.contains("Cycle"));
        }
    }

    #[test]
    fn test_validate_dag_missing_dep() {
        let tasks = vec![
            make_test_task("T1", vec!["T999"]), // T999 doesn't exist
        ];

        let result = validate_dag(&tasks);
        assert!(matches!(result, Err(DagGenError::InvalidDag(_))));
        if let Err(DagGenError::InvalidDag(msg)) = result {
            assert!(msg.contains("non-existent"));
        }
    }

    #[test]
    fn test_parse_task_list_wrapper_object() {
        let json = r#"{"tasks": [
            {
                "id": "T1",
                "description": "Research API",
                "dependencies": [],
                "task_type": "research",
                "priority": "Normal",
                "complexity": "Simple",
                "skill_hint": null
            },
            {
                "id": "T2",
                "description": "Implement",
                "dependencies": ["T1"],
                "task_type": "implement",
                "priority": "Normal",
                "complexity": "Medium",
                "skill_hint": null
            }
        ]}"#;

        let tasks = parse_task_list(json).unwrap();
        assert_eq!(tasks.len(), 2);
        assert_eq!(tasks[0].id, "T1");
        assert_eq!(tasks[1].dependencies, vec!["T1"]);
    }

    #[test]
    fn test_validate_dag_self_reference() {
        let tasks = vec![
            GeneratedTask {
                id: "T1".to_string(),
                description: "Task".to_string(),
                dependencies: vec!["T1".to_string()], // Self-reference!
                task_type: TaskType::Implement,
                priority: Priority::Normal,
                complexity: Complexity::Medium,
                skill_hint: None,
            },
        ];

        let result = validate_dag(&tasks);
        assert!(matches!(result, Err(DagGenError::InvalidDag(_))));
        if let Err(DagGenError::InvalidDag(msg)) = result {
            assert!(msg.contains("depends on itself"));
        }
    }
}
